# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a55a5d6f19d0e8e7f91c2a7a16721c6"
name = "Prophet CI Platform"
handle = "prophet-customer-intelligence"
application_url = "https://prophet-beta.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products, read_orders, read_all_orders, read_customers, read_returns, read_inventory, read_shipping"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

    [[webhooks.subscriptions]]
  topics = [ "app/checkouts_create" ]
  uri = "/webhooks/app/checkouts/create"

    [[webhooks.subscriptions]]
  topics = [ "app/checkouts_update" ]
  uri = "/webhooks/app/checkouts/update"

    [[webhooks.subscriptions]]
  topics = [ "app/orders_create" ]
  uri = "/webhooks/app/orders/create"

    [[webhooks.subscriptions]]
  topics = [ "app/orders_update" ]
  uri = "/webhooks/app/orders/update"

    [[webhooks.subscriptions]]
  topics = [ "app/orders_fulfilled" ]
  uri = "/webhooks/app/orders/fulfilled"

    [[webhooks.subsubscriptions]]
  topics = [ "app/orders_cancelled" ]
  uri = "/webhooks/app/orders/cancelled"

    [[webhooks.subscriptions]]
  topics = [ "app/app_subscriptions_update" ]
  uri = "/webhooks/app/app_susbscriptions/update"

    [[webhooks.subscriptions]]
  topics = [ "app/app_subscriptions_cancelled" ]
  uri = "/webhooks/app/app_subscriptions/cancelled"

    [[webhooks.subscriptions]]
topics = [ "app/subscription_billing_attempt_success" ]
uri = "/webhooks/app/subscription_billing_attempt/success"

  [[webhooks.subscriptions]]
topics = [ "app/subscription_billing_attmept_failure" ]
uri = "/webhooks/app/subscription_billing_attempt/failure"

  [[webhooks.subscriptions]]
  uri = "https://jqqmquuomykzdeplumki.supabase.co/functions/v1/gdpr-request"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = ["https://prophet-beta.vercel.app/auth/, https://prophet-beta.vercel.app/auth"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true
dev_store_url = "oldetownehardware.myshopify.com"
