# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a55a5d6f19d0e8e7f91c2a7a16721c6"
name = "Prophet CI Platform"
handle = "prophet-customer-intelligence"
application_url = "https://prophet-beta.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products, read_orders, read_all_orders, read_customers, read_returns, read_inventory, read_shipping, write_customers, write_discounts, read_discounts, read_metaobject_definitions, read_metaobjects, write_metaobject_definitions, write_metaobjects, write_products,write_themes"

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "app/scopes_update"]
uri = "/webhooks/app/events"


[[webhooks.subscriptions]]
topics = ["orders/create", "orders/fulfilled", "orders/updated"]
uri = "/webhooks/orders"

[[webhooks.subscriptions]]
topics = ["checkouts/create", "checkouts/update"]
uri = "/webhooks/checkouts"


[[webhooks.subscriptions]]
  uri = "https://jqqmquuomykzdeplumki.supabase.co/functions/v1/gdpr-request"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = ["https://prophet-beta.vercel.app/auth/", "https://prophet-beta.vercel.app/auth"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "oldetownehardware.myshopify.com"
