# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a55a5d6f19d0e8e7f91c2a7a16721c6"
name = "Prophet CI Platform"
handle = "prophet-customer-intelligence"
application_url = "https://prophet-beta.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products, read_orders, read_all_orders, read_customers, read_returns,
read_inventory, read_shipping, write_customers, write_discounts, read_discounts, 
read_metaobject_definitions, read_metaobjects, write_metaobject_definitions, 
write_metaobjects, write_products,write_themes, write_app_proxy"

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app-uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/scopes-update"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/orders-create"

[[webhooks.subscriptions]]
topics = ["orders/fulfilled"] 
uri = "/webhooks/orders-fulfilled"

[[webhooks.subscriptions]]
topics = ["orders/updated"]
uri = "/webhooks/orders-updated"

[[webhooks.subscriptions]]
topics = ["orders/cancelled"]
uri = "/webhooks/orders-cancelled"

[[webhooks.subscriptions]]
topics = ["checkouts/create"]
uri = "/webhooks/checkouts-create"

[[webhooks.subscriptions]]
topics = ["checkouts/update"]
uri = "/webhooks/checkouts-update"

[[webhooks.subscriptions]]
topics = [ "customers/data_request" ]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topics = [ "customers/redact" ]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = [ "shop/redact" ]
uri = "/webhooks/shop/redact"


[auth]
redirect_urls = ["https://prophet-beta.vercel.app/auth/", 
"https://prophet-beta.vercel.app/auth"]

[pos]
embedded = false

[app_proxy]
url = "https://prophet-beta.vercel.app/apps/process-offer" 
prefix = "apps"                               
subpath = "process-offer"                               

[build]
automatically_update_urls_on_dev = false
dev_store_url = "oldetownehardware.myshopify.com"
