
scopes = "read_products, read_orders, read_customers, read_discounts, read_categories, read_collections, read_variants, read_inventory"

[webhooks]
api_version = "2024-10"

# Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

# Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

           
# Mandatory compliance topic for public apps only
 
[[webhooks.subscriptions]]
uri = "https://jqqmquuomykzdeplumki.supabase.co/functions/v1/gdpr-request"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "https://jqqmquuomykzdeplumki.supabase.co/functions/v1/gdpr-request"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "https://jqqmquuomykzdeplumki.supabase.co/functions/v1/gdpr-request"
compliance_topics = ["shop/redact"]
