api_version = "2025-07"

# Existing theme extension (App Block)
[[extensions]]
name = "I Want That!"
type = "theme"
handle="iwt-offers"
uid = "c516f42f-fb66-7747-b74f-39a9f9836ae34425ce17"
description = "Customer Generated Offers"

[extensions.capabilities]
  api_access = true


